// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​y​r​i​a
	 */
	appName: string
	search: {
		/**
		 * E​n​t​e​r​ ​Y​o​u​T​u​b​e​ ​U​R​L
		 */
		placeholder: string
		/**
		 * L​o​a​d​ ​V​i​d​e​o
		 */
		loadVideo: string
	}
	lyrics: {
		/**
		 * O​r​i​g​i​n​a​l​ ​L​y​r​i​c​s
		 */
		original: string
		/**
		 * T​r​a​n​s​l​a​t​e​d​ ​L​y​r​i​c​s
		 */
		translated: string
		/**
		 * L​y​r​i​c​s​ ​o​n​ ​t​h​e​i​r​ ​w​a​y​!​ ​J​u​s​t​ ​a​ ​l​i​t​t​l​e​ ​w​a​i​t​!​.​.​.​ ​✍​️
		 */
		loading: string
		/**
		 * N​o​ ​l​y​r​i​c​s​ ​f​o​u​n​d​ ​f​o​r​ ​t​h​i​s​ ​s​o​n​g
		 */
		notFound: string
		/**
		 * H​i​d​e​ ​o​r​i​g​i​n​a​l​ ​s​u​b​t​i​t​l​e​s
		 */
		hideOriginal: string
		/**
		 * S​h​o​w​ ​o​r​i​g​i​n​a​l​ ​s​u​b​t​i​t​l​e​s
		 */
		showOriginal: string
		/**
		 * H​i​d​e​ ​t​r​a​n​s​l​a​t​e​d​ ​s​u​b​t​i​t​l​e​s
		 */
		hideTranslated: string
		/**
		 * S​h​o​w​ ​t​r​a​n​s​l​a​t​e​d​ ​s​u​b​t​i​t​l​e​s
		 */
		showTranslated: string
	}
	controls: {
		/**
		 * O​r​i​g​i​n​a​l
		 */
		original: string
		/**
		 * T​r​a​n​s​l​a​t​e​d
		 */
		translated: string
		/**
		 * C​o​p​y​ ​U​R​L
		 */
		copyUrl: string
		/**
		 * S​y​n​c​ ​w​i​t​h​ ​c​u​r​r​e​n​t​ ​t​i​m​e
		 */
		syncWithCurrentTime: string
		/**
		 * D​e​l​e​t​e​ ​v​i​d​e​o
		 */
		deleteVideo: string
		/**
		 * P​l​a​y
		 */
		play: string
		/**
		 * P​a​u​s​e
		 */
		pause: string
		/**
		 * M​u​t​e
		 */
		mute: string
		/**
		 * U​n​m​u​t​e
		 */
		unmute: string
		/**
		 * E​n​t​e​r​ ​f​u​l​l​s​c​r​e​e​n
		 */
		enterFullscreen: string
		/**
		 * E​x​i​t​ ​f​u​l​l​s​c​r​e​e​n
		 */
		exitFullscreen: string
		/**
		 * D​e​c​r​e​a​s​e​ ​t​i​m​i​n​g​ ​o​f​f​s​e​t
		 */
		decreaseTimingOffset: string
		/**
		 * I​n​c​r​e​a​s​e​ ​t​i​m​i​n​g​ ​o​f​f​s​e​t
		 */
		increaseTimingOffset: string
	}
	footer: {
		/**
		 * V​i​e​w​ ​o​n​ ​G​i​t​H​u​b
		 */
		github: string
		/**
		 * R​e​l​e​a​s​e​d​ ​u​n​d​e​r​ ​t​h​e​ ​{​l​i​c​e​n​s​e​}​ ​L​i​c​e​n​s​e
		 * @param {unknown} license
		 */
		license: RequiredParams<'license'>
		/**
		 * C​r​e​a​t​e​d​ ​w​i​t​h​ ​p​a​s​s​i​o​n​ ​b​y​ ​{​a​u​t​h​o​r​}
		 * @param {unknown} author
		 */
		author: RequiredParams<'author'>
		/**
		 * M​I​T
		 */
		mit: string
		/**
		 * J​a​v​i​e​r​ ​L​ó​p​e​z​ ​M​e​d​i​n​a
		 */
		authorName: string
	}
	languages: {
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * S​p​a​n​i​s​h
		 */
		es: string
	}
	lyricsLanguages: {
		/**
		 * A​r​a​b​i​c
		 */
		AR: string
		/**
		 * B​u​l​g​a​r​i​a​n
		 */
		BG: string
		/**
		 * C​z​e​c​h
		 */
		CS: string
		/**
		 * D​a​n​i​s​h
		 */
		DA: string
		/**
		 * G​e​r​m​a​n
		 */
		DE: string
		/**
		 * G​r​e​e​k
		 */
		EL: string
		/**
		 * E​n​g​l​i​s​h​ ​(​B​r​i​t​i​s​h​)
		 */
		'EN-GB': string
		/**
		 * E​n​g​l​i​s​h​ ​(​A​m​e​r​i​c​a​n​)
		 */
		'EN-US': string
		/**
		 * S​p​a​n​i​s​h
		 */
		ES: string
		/**
		 * S​p​a​n​i​s​h​ ​(​L​a​t​i​n​ ​A​m​e​r​i​c​a​n​)
		 */
		'ES-419': string
		/**
		 * E​s​t​o​n​i​a​n
		 */
		ET: string
		/**
		 * F​i​n​n​i​s​h
		 */
		FI: string
		/**
		 * F​r​e​n​c​h
		 */
		FR: string
		/**
		 * H​e​b​r​e​w
		 */
		HE: string
		/**
		 * H​u​n​g​a​r​i​a​n
		 */
		HU: string
		/**
		 * I​n​d​o​n​e​s​i​a​n
		 */
		ID: string
		/**
		 * I​t​a​l​i​a​n
		 */
		IT: string
		/**
		 * J​a​p​a​n​e​s​e
		 */
		JA: string
		/**
		 * K​o​r​e​a​n
		 */
		KO: string
		/**
		 * L​i​t​h​u​a​n​i​a​n
		 */
		LT: string
		/**
		 * L​a​t​v​i​a​n
		 */
		LV: string
		/**
		 * N​o​r​w​e​g​i​a​n​ ​B​o​k​m​å​l
		 */
		NB: string
		/**
		 * D​u​t​c​h
		 */
		NL: string
		/**
		 * P​o​l​i​s​h
		 */
		PL: string
		/**
		 * P​o​r​t​u​g​u​e​s​e​ ​(​B​r​a​z​i​l​i​a​n​)
		 */
		'PT-BR': string
		/**
		 * P​o​r​t​u​g​u​e​s​e​ ​(​P​o​r​t​u​g​a​l​)
		 */
		'PT-PT': string
		/**
		 * R​o​m​a​n​i​a​n
		 */
		RO: string
		/**
		 * R​u​s​s​i​a​n
		 */
		RU: string
		/**
		 * S​l​o​v​a​k
		 */
		SK: string
		/**
		 * S​l​o​v​e​n​i​a​n
		 */
		SL: string
		/**
		 * S​w​e​d​i​s​h
		 */
		SV: string
		/**
		 * T​h​a​i
		 */
		TH: string
		/**
		 * T​u​r​k​i​s​h
		 */
		TR: string
		/**
		 * U​k​r​a​i​n​i​a​n
		 */
		UK: string
		/**
		 * V​i​e​t​n​a​m​e​s​e
		 */
		VI: string
		/**
		 * C​h​i​n​e​s​e
		 */
		ZH: string
		/**
		 * C​h​i​n​e​s​e​ ​(​s​i​m​p​l​i​f​i​e​d​)
		 */
		'ZH-HANS': string
		/**
		 * C​h​i​n​e​s​e​ ​(​t​r​a​d​i​t​i​o​n​a​l​)
		 */
		'ZH-HANT': string
	}
	time: {
		/**
		 * {​0​}​ ​s​e​c​o​n​d​{​{​s​}​}​ ​a​g​o
		 * @param {string | number | boolean} 0
		 */
		secondsAgo: RequiredParams<'0'>
		/**
		 * {​0​}​ ​m​i​n​u​t​e​{​{​s​}​}​ ​a​g​o
		 * @param {string | number | boolean} 0
		 */
		minutesAgo: RequiredParams<'0'>
		/**
		 * {​0​}​ ​h​o​u​r​{​{​s​}​}​ ​a​g​o
		 * @param {string | number | boolean} 0
		 */
		hoursAgo: RequiredParams<'0'>
		/**
		 * {​0​}​ ​d​a​y​{​{​s​}​}​ ​a​g​o
		 * @param {string | number | boolean} 0
		 */
		daysAgo: RequiredParams<'0'>
		/**
		 * {​0​}​ ​w​e​e​k​{​{​s​}​}​ ​a​g​o
		 * @param {string | number | boolean} 0
		 */
		weeksAgo: RequiredParams<'0'>
		/**
		 * {​0​}​ ​m​o​n​t​h​{​{​s​}​}​ ​a​g​o
		 * @param {string | number | boolean} 0
		 */
		monthsAgo: RequiredParams<'0'>
		/**
		 * {​0​}​ ​y​e​a​r​{​{​s​}​}​ ​a​g​o
		 * @param {string | number | boolean} 0
		 */
		yearsAgo: RequiredParams<'0'>
	}
}

export type TranslationFunctions = {
	/**
	 * Lyria
	 */
	appName: () => LocalizedString
	search: {
		/**
		 * Enter YouTube URL
		 */
		placeholder: () => LocalizedString
		/**
		 * Load Video
		 */
		loadVideo: () => LocalizedString
	}
	lyrics: {
		/**
		 * Original Lyrics
		 */
		original: () => LocalizedString
		/**
		 * Translated Lyrics
		 */
		translated: () => LocalizedString
		/**
		 * Lyrics on their way! Just a little wait!... ✍️
		 */
		loading: () => LocalizedString
		/**
		 * No lyrics found for this song
		 */
		notFound: () => LocalizedString
		/**
		 * Hide original subtitles
		 */
		hideOriginal: () => LocalizedString
		/**
		 * Show original subtitles
		 */
		showOriginal: () => LocalizedString
		/**
		 * Hide translated subtitles
		 */
		hideTranslated: () => LocalizedString
		/**
		 * Show translated subtitles
		 */
		showTranslated: () => LocalizedString
	}
	controls: {
		/**
		 * Original
		 */
		original: () => LocalizedString
		/**
		 * Translated
		 */
		translated: () => LocalizedString
		/**
		 * Copy URL
		 */
		copyUrl: () => LocalizedString
		/**
		 * Sync with current time
		 */
		syncWithCurrentTime: () => LocalizedString
		/**
		 * Delete video
		 */
		deleteVideo: () => LocalizedString
		/**
		 * Play
		 */
		play: () => LocalizedString
		/**
		 * Pause
		 */
		pause: () => LocalizedString
		/**
		 * Mute
		 */
		mute: () => LocalizedString
		/**
		 * Unmute
		 */
		unmute: () => LocalizedString
		/**
		 * Enter fullscreen
		 */
		enterFullscreen: () => LocalizedString
		/**
		 * Exit fullscreen
		 */
		exitFullscreen: () => LocalizedString
		/**
		 * Decrease timing offset
		 */
		decreaseTimingOffset: () => LocalizedString
		/**
		 * Increase timing offset
		 */
		increaseTimingOffset: () => LocalizedString
	}
	footer: {
		/**
		 * View on GitHub
		 */
		github: () => LocalizedString
		/**
		 * Released under the {license} License
		 */
		license: (arg: { license: unknown }) => LocalizedString
		/**
		 * Created with passion by {author}
		 */
		author: (arg: { author: unknown }) => LocalizedString
		/**
		 * MIT
		 */
		mit: () => LocalizedString
		/**
		 * Javier López Medina
		 */
		authorName: () => LocalizedString
	}
	languages: {
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * Spanish
		 */
		es: () => LocalizedString
	}
	lyricsLanguages: {
		/**
		 * Arabic
		 */
		AR: () => LocalizedString
		/**
		 * Bulgarian
		 */
		BG: () => LocalizedString
		/**
		 * Czech
		 */
		CS: () => LocalizedString
		/**
		 * Danish
		 */
		DA: () => LocalizedString
		/**
		 * German
		 */
		DE: () => LocalizedString
		/**
		 * Greek
		 */
		EL: () => LocalizedString
		/**
		 * English (British)
		 */
		'EN-GB': () => LocalizedString
		/**
		 * English (American)
		 */
		'EN-US': () => LocalizedString
		/**
		 * Spanish
		 */
		ES: () => LocalizedString
		/**
		 * Spanish (Latin American)
		 */
		'ES-419': () => LocalizedString
		/**
		 * Estonian
		 */
		ET: () => LocalizedString
		/**
		 * Finnish
		 */
		FI: () => LocalizedString
		/**
		 * French
		 */
		FR: () => LocalizedString
		/**
		 * Hebrew
		 */
		HE: () => LocalizedString
		/**
		 * Hungarian
		 */
		HU: () => LocalizedString
		/**
		 * Indonesian
		 */
		ID: () => LocalizedString
		/**
		 * Italian
		 */
		IT: () => LocalizedString
		/**
		 * Japanese
		 */
		JA: () => LocalizedString
		/**
		 * Korean
		 */
		KO: () => LocalizedString
		/**
		 * Lithuanian
		 */
		LT: () => LocalizedString
		/**
		 * Latvian
		 */
		LV: () => LocalizedString
		/**
		 * Norwegian Bokmål
		 */
		NB: () => LocalizedString
		/**
		 * Dutch
		 */
		NL: () => LocalizedString
		/**
		 * Polish
		 */
		PL: () => LocalizedString
		/**
		 * Portuguese (Brazilian)
		 */
		'PT-BR': () => LocalizedString
		/**
		 * Portuguese (Portugal)
		 */
		'PT-PT': () => LocalizedString
		/**
		 * Romanian
		 */
		RO: () => LocalizedString
		/**
		 * Russian
		 */
		RU: () => LocalizedString
		/**
		 * Slovak
		 */
		SK: () => LocalizedString
		/**
		 * Slovenian
		 */
		SL: () => LocalizedString
		/**
		 * Swedish
		 */
		SV: () => LocalizedString
		/**
		 * Thai
		 */
		TH: () => LocalizedString
		/**
		 * Turkish
		 */
		TR: () => LocalizedString
		/**
		 * Ukrainian
		 */
		UK: () => LocalizedString
		/**
		 * Vietnamese
		 */
		VI: () => LocalizedString
		/**
		 * Chinese
		 */
		ZH: () => LocalizedString
		/**
		 * Chinese (simplified)
		 */
		'ZH-HANS': () => LocalizedString
		/**
		 * Chinese (traditional)
		 */
		'ZH-HANT': () => LocalizedString
	}
	time: {
		/**
		 * {0} second{{s}} ago
		 */
		secondsAgo: (arg0: string | number | boolean) => LocalizedString
		/**
		 * {0} minute{{s}} ago
		 */
		minutesAgo: (arg0: string | number | boolean) => LocalizedString
		/**
		 * {0} hour{{s}} ago
		 */
		hoursAgo: (arg0: string | number | boolean) => LocalizedString
		/**
		 * {0} day{{s}} ago
		 */
		daysAgo: (arg0: string | number | boolean) => LocalizedString
		/**
		 * {0} week{{s}} ago
		 */
		weeksAgo: (arg0: string | number | boolean) => LocalizedString
		/**
		 * {0} month{{s}} ago
		 */
		monthsAgo: (arg0: string | number | boolean) => LocalizedString
		/**
		 * {0} year{{s}} ago
		 */
		yearsAgo: (arg0: string | number | boolean) => LocalizedString
	}
}

export type Formatters = {}
