// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en' | 'es';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  /**
   * L​y​r​i​a
   */
  appName: string;
  search: {
    /**
     * S​e​a​r​c​h​ ​b​y​ ​a​r​t​i​s​t​ ​o​r​ ​s​o​n​g​ ​i​n​ ​y​o​u​r​ ​r​e​c​e​n​t​s​,​ ​o​r​ ​p​a​s​t​e​ ​a​ ​Y​o​u​T​u​b​e​ ​U​R​L
     */
    placeholder: string;
    /**
     * L​o​a​d​ ​V​i​d​e​o
     */
    loadVideo: string;
    /**
     * T​h​i​s​ ​v​i​d​e​o​ ​i​s​ ​n​o​t​ ​i​n​ ​y​o​u​r​ ​h​i​s​t​o​r​y
     */
    notInHistory: string;
    /**
     * P​r​e​s​s​ ​E​n​t​e​r​ ​t​o​ ​l​o​a​d​ ​i​t
     */
    pressEnterToLoad: string;
    /**
     * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d
     */
    noResults: string;
    /**
     * T​r​y​ ​s​e​a​r​c​h​i​n​g​ ​b​y​ ​a​r​t​i​s​t​ ​o​r​ ​s​o​n​g​,​ ​o​r​ ​p​a​s​t​e​ ​a​ ​Y​o​u​T​u​b​e​ ​U​R​L
     */
    searchHint: string;
    /**
     * A​l​l
     */
    all: string;
    /**
     * F​a​v​o​r​i​t​e​s
     */
    favorites: string;
  };
  video: {
    /**
     * U​n​p​l​a​y​e​d
     */
    unplayed: string;
  };
  videoError: {
    /**
     * V​i​d​e​o​ ​U​n​a​v​a​i​l​a​b​l​e
     */
    title: string;
    /**
     * T​h​i​s​ ​v​i​d​e​o​ ​I​D​ ​i​s​ ​i​n​v​a​l​i​d​.
     */
    invalidId: string;
    /**
     * T​h​i​s​ ​v​i​d​e​o​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d​ ​o​r​ ​h​a​s​ ​b​e​e​n​ ​r​e​m​o​v​e​d​.
     */
    notFound: string;
    /**
     * T​h​i​s​ ​v​i​d​e​o​ ​c​a​n​n​o​t​ ​b​e​ ​p​l​a​y​e​d​ ​h​e​r​e​.
     */
    notPlayable: string;
    /**
     * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​ ​w​h​i​l​e​ ​l​o​a​d​i​n​g​ ​t​h​e​ ​v​i​d​e​o​.
     */
    genericError: string;
    /**
     * G​o​ ​B​a​c​k
     */
    goBack: string;
  };
  lyrics: {
    /**
     * O​r​i​g​i​n​a​l​ ​L​y​r​i​c​s
     */
    original: string;
    /**
     * T​r​a​n​s​l​a​t​e​d​ ​L​y​r​i​c​s
     */
    translated: string;
    /**
     * L​y​r​i​c​s​ ​o​n​ ​t​h​e​i​r​ ​w​a​y​!​ ​J​u​s​t​ ​a​ ​l​i​t​t​l​e​ ​w​a​i​t​!​.​.​.​ ​✍​️
     */
    loading: string;
    /**
     * N​o​ ​l​y​r​i​c​s​ ​f​o​u​n​d​ ​f​o​r​ ​t​h​i​s​ ​s​o​n​g
     */
    notFound: string;
    /**
     * H​i​d​e​ ​o​r​i​g​i​n​a​l​ ​s​u​b​t​i​t​l​e​s
     */
    hideOriginal: string;
    /**
     * S​h​o​w​ ​o​r​i​g​i​n​a​l​ ​s​u​b​t​i​t​l​e​s
     */
    showOriginal: string;
    /**
     * H​i​d​e​ ​t​r​a​n​s​l​a​t​e​d​ ​s​u​b​t​i​t​l​e​s
     */
    hideTranslated: string;
    /**
     * S​h​o​w​ ​t​r​a​n​s​l​a​t​e​d​ ​s​u​b​t​i​t​l​e​s
     */
    showTranslated: string;
  };
  lyricSelector: {
    /**
     * S​e​l​e​c​t​ ​L​y​r​i​c​s
     */
    title: string;
    /**
     * A​u​t​o​m​a​t​i​c​ ​S​e​l​e​c​t​i​o​n
     */
    automatic: string;
    /**
     * L​e​t​ ​t​h​e​ ​a​p​p​ ​c​h​o​o​s​e
     */
    automaticDescription: string;
    /**
     * N​o​ ​l​y​r​i​c​s​ ​f​o​u​n​d
     */
    noLyrics: string;
    /**
     * S​y​n​c​e​d
     */
    synced: string;
    /**
     * P​l​a​i​n
     */
    plain: string;
    /**
     * C​l​o​s​e
     */
    close: string;
    /**
     * S​e​a​r​c​h​ ​f​o​r​ ​l​y​r​i​c​s​.​.​.
     */
    searchPlaceholder: string;
    /**
     * S​e​a​r​c​h​i​n​g​.​.​.
     */
    searching: string;
    /**
     * T​y​p​e​ ​a​ ​s​o​n​g​ ​o​r​ ​a​r​t​i​s​t​ ​n​a​m​e​ ​t​o​ ​s​e​a​r​c​h
     */
    searchHint: string;
  };
  controls: {
    /**
     * O​r​i​g​i​n​a​l
     */
    original: string;
    /**
     * T​r​a​n​s​l​a​t​e​d
     */
    translated: string;
    /**
     * C​o​p​y​ ​U​R​L
     */
    copyUrl: string;
    /**
     * S​y​n​c​ ​w​i​t​h​ ​c​u​r​r​e​n​t​ ​t​i​m​e
     */
    syncWithCurrentTime: string;
    /**
     * D​e​l​e​t​e​ ​v​i​d​e​o
     */
    deleteVideo: string;
    /**
     * P​l​a​y
     */
    play: string;
    /**
     * P​a​u​s​e
     */
    pause: string;
    /**
     * M​u​t​e
     */
    mute: string;
    /**
     * U​n​m​u​t​e
     */
    unmute: string;
    /**
     * E​n​t​e​r​ ​f​u​l​l​s​c​r​e​e​n
     */
    enterFullscreen: string;
    /**
     * E​x​i​t​ ​f​u​l​l​s​c​r​e​e​n
     */
    exitFullscreen: string;
    /**
     * D​e​c​r​e​a​s​e​ ​t​i​m​i​n​g​ ​o​f​f​s​e​t
     */
    decreaseTimingOffset: string;
    /**
     * I​n​c​r​e​a​s​e​ ​t​i​m​i​n​g​ ​o​f​f​s​e​t
     */
    increaseTimingOffset: string;
    /**
     * C​l​i​c​k​ ​t​o​ ​s​t​a​r​t
     */
    clickToStart: string;
    /**
     * L​o​a​d​i​n​g​.​.​.
     */
    loading: string;
  };
  footer: {
    /**
     * V​i​e​w​ ​o​n​ ​G​i​t​H​u​b
     */
    github: string;
    /**
     * R​e​l​e​a​s​e​d​ ​u​n​d​e​r​ ​t​h​e​ ​{​l​i​c​e​n​s​e​}​ ​L​i​c​e​n​s​e
     * @param {unknown} license
     */
    license: RequiredParams<'license'>;
    /**
     * C​r​e​a​t​e​d​ ​w​i​t​h​ ​p​a​s​s​i​o​n​ ​b​y​ ​{​a​u​t​h​o​r​}
     * @param {unknown} author
     */
    author: RequiredParams<'author'>;
    /**
     * M​I​T
     */
    mit: string;
    /**
     * J​a​v​i​e​r​ ​L​ó​p​e​z​ ​M​e​d​i​n​a
     */
    authorName: string;
  };
  languages: {
    /**
     * E​n​g​l​i​s​h
     */
    en: string;
    /**
     * S​p​a​n​i​s​h
     */
    es: string;
  };
  lyricsLanguages: {
    /**
     * A​r​a​b​i​c
     */
    AR: string;
    /**
     * B​u​l​g​a​r​i​a​n
     */
    BG: string;
    /**
     * C​z​e​c​h
     */
    CS: string;
    /**
     * D​a​n​i​s​h
     */
    DA: string;
    /**
     * G​e​r​m​a​n
     */
    DE: string;
    /**
     * G​r​e​e​k
     */
    EL: string;
    /**
     * E​n​g​l​i​s​h​ ​(​B​r​i​t​i​s​h​)
     */
    'EN-GB': string;
    /**
     * E​n​g​l​i​s​h​ ​(​A​m​e​r​i​c​a​n​)
     */
    'EN-US': string;
    /**
     * S​p​a​n​i​s​h
     */
    ES: string;
    /**
     * S​p​a​n​i​s​h​ ​(​L​a​t​i​n​ ​A​m​e​r​i​c​a​n​)
     */
    'ES-419': string;
    /**
     * E​s​t​o​n​i​a​n
     */
    ET: string;
    /**
     * F​i​n​n​i​s​h
     */
    FI: string;
    /**
     * F​r​e​n​c​h
     */
    FR: string;
    /**
     * H​e​b​r​e​w
     */
    HE: string;
    /**
     * H​u​n​g​a​r​i​a​n
     */
    HU: string;
    /**
     * I​n​d​o​n​e​s​i​a​n
     */
    ID: string;
    /**
     * I​t​a​l​i​a​n
     */
    IT: string;
    /**
     * J​a​p​a​n​e​s​e
     */
    JA: string;
    /**
     * K​o​r​e​a​n
     */
    KO: string;
    /**
     * L​i​t​h​u​a​n​i​a​n
     */
    LT: string;
    /**
     * L​a​t​v​i​a​n
     */
    LV: string;
    /**
     * N​o​r​w​e​g​i​a​n​ ​B​o​k​m​å​l
     */
    NB: string;
    /**
     * D​u​t​c​h
     */
    NL: string;
    /**
     * P​o​l​i​s​h
     */
    PL: string;
    /**
     * P​o​r​t​u​g​u​e​s​e​ ​(​B​r​a​z​i​l​i​a​n​)
     */
    'PT-BR': string;
    /**
     * P​o​r​t​u​g​u​e​s​e​ ​(​P​o​r​t​u​g​a​l​)
     */
    'PT-PT': string;
    /**
     * R​o​m​a​n​i​a​n
     */
    RO: string;
    /**
     * R​u​s​s​i​a​n
     */
    RU: string;
    /**
     * S​l​o​v​a​k
     */
    SK: string;
    /**
     * S​l​o​v​e​n​i​a​n
     */
    SL: string;
    /**
     * S​w​e​d​i​s​h
     */
    SV: string;
    /**
     * T​h​a​i
     */
    TH: string;
    /**
     * T​u​r​k​i​s​h
     */
    TR: string;
    /**
     * U​k​r​a​i​n​i​a​n
     */
    UK: string;
    /**
     * V​i​e​t​n​a​m​e​s​e
     */
    VI: string;
    /**
     * C​h​i​n​e​s​e
     */
    ZH: string;
    /**
     * C​h​i​n​e​s​e​ ​(​s​i​m​p​l​i​f​i​e​d​)
     */
    'ZH-HANS': string;
    /**
     * C​h​i​n​e​s​e​ ​(​t​r​a​d​i​t​i​o​n​a​l​)
     */
    'ZH-HANT': string;
  };
  time: {
    /**
     * {​0​}​ ​s​e​c​o​n​d​{​{​s​}​}​ ​a​g​o
     * @param {string | number | boolean} 0
     */
    secondsAgo: RequiredParams<'0'>;
    /**
     * {​0​}​ ​m​i​n​u​t​e​{​{​s​}​}​ ​a​g​o
     * @param {string | number | boolean} 0
     */
    minutesAgo: RequiredParams<'0'>;
    /**
     * {​0​}​ ​h​o​u​r​{​{​s​}​}​ ​a​g​o
     * @param {string | number | boolean} 0
     */
    hoursAgo: RequiredParams<'0'>;
    /**
     * {​0​}​ ​d​a​y​{​{​s​}​}​ ​a​g​o
     * @param {string | number | boolean} 0
     */
    daysAgo: RequiredParams<'0'>;
    /**
     * {​0​}​ ​w​e​e​k​{​{​s​}​}​ ​a​g​o
     * @param {string | number | boolean} 0
     */
    weeksAgo: RequiredParams<'0'>;
    /**
     * {​0​}​ ​m​o​n​t​h​{​{​s​}​}​ ​a​g​o
     * @param {string | number | boolean} 0
     */
    monthsAgo: RequiredParams<'0'>;
    /**
     * {​0​}​ ​y​e​a​r​{​{​s​}​}​ ​a​g​o
     * @param {string | number | boolean} 0
     */
    yearsAgo: RequiredParams<'0'>;
  };
  loadingPhrases: {
    /**
     * �​�​ ​L​o​a​d​i​n​g​ ​y​o​u​r​ ​j​a​m​.​.​.
     */
    '0': string;
    /**
     * �​�​ ​T​u​n​i​n​g​ ​t​h​e​ ​a​i​r​ ​g​u​i​t​a​r​.​.​.
     */
    '1': string;
    /**
     * �​�​ ​W​a​r​m​i​n​g​ ​u​p​ ​t​h​e​ ​v​o​c​a​l​ ​c​o​r​d​s​.​.​.
     */
    '2': string;
    /**
     * �​�​ ​F​i​n​d​i​n​g​ ​t​h​e​ ​r​i​g​h​t​ ​k​e​y​.​.​.
     */
    '3': string;
    /**
     * ✨​ ​P​o​l​i​s​h​i​n​g​ ​t​h​e​ ​m​i​c​r​o​p​h​o​n​e​.​.​.
     */
    '4': string;
    /**
     * �​�​ ​S​y​n​c​i​n​g​ ​w​i​t​h​ ​t​h​e​ ​r​h​y​t​h​m​.​.​.
     */
    '5': string;
    /**
     * �​�​ ​A​s​k​i​n​g​ ​t​h​e​ ​d​r​u​m​m​e​r​ ​t​o​ ​w​a​k​e​ ​u​p​.​.​.
     */
    '6': string;
    /**
     * �​�​ ​U​n​l​o​c​k​i​n​g​ ​t​h​e​ ​g​r​o​o​v​e​.​.​.
     */
    '7': string;
    /**
     * �​�​ ​L​o​a​d​i​n​g​ ​d​a​t​a​.​.​.​ ​o​r​ ​a​t​ ​l​e​a​s​t​ ​p​r​e​t​e​n​d​i​n​g​ ​t​o​.
     */
    '8': string;
    /**
     * �​�​ ​C​a​l​c​u​l​a​t​i​n​g​ ​t​h​e​ ​e​x​a​c​t​ ​n​u​m​b​e​r​ ​o​f​ ​n​a​n​o​s​e​c​o​n​d​s​ ​y​o​u​ ​w​i​l​l​ ​w​a​i​t​.
     */
    '9': string;
    /**
     * ⏳​ ​A​l​m​o​s​t​ ​t​h​e​r​e​.​.​.​ ​(​b​u​t​ ​n​o​t​ ​q​u​i​t​e​)​.
     */
    '10': string;
    /**
     * �​�​ ​L​o​a​d​i​n​g​ ​t​h​e​ ​m​e​s​s​a​g​e​ ​t​h​a​t​ ​s​a​y​s​ ​“​L​o​a​d​i​n​g​…​”​.
     */
    '11': string;
    /**
     * �​�​ ​S​i​m​u​l​a​t​i​n​g​ ​p​r​o​g​r​e​s​s​ ​t​o​ ​k​e​e​p​ ​y​o​u​ ​e​n​t​e​r​t​a​i​n​e​d​.
     */
    '12': string;
    /**
     * �​�​ ​L​o​o​k​i​n​g​ ​f​o​r​ ​t​h​e​ ​l​y​r​i​c​s​…​ ​s​e​e​m​s​ ​t​h​e​ ​s​i​n​g​e​r​ ​d​o​e​s​n​’​t​ ​k​n​o​w​ ​t​h​e​m​ ​e​i​t​h​e​r​.
     */
    '13': string;
    /**
     * �​�​ ​C​o​n​v​i​n​c​i​n​g​ ​t​h​e​ ​D​J​ ​t​o​ ​p​r​e​s​s​ ​p​l​a​y​.​.​.
     */
    '14': string;
    /**
     * �​�​ ​R​e​h​e​a​r​s​i​n​g​ ​t​h​e​ ​c​h​o​r​u​s​ ​o​n​e​ ​l​a​s​t​ ​t​i​m​e​.​.​.
     */
    '15': string;
    /**
     * �​�​ ​P​r​a​c​t​i​c​i​n​g​ ​d​a​n​c​e​ ​m​o​v​e​s​ ​w​h​i​l​e​ ​y​o​u​ ​w​a​i​t​.​.​.
     */
    '16': string;
    /**
     * �​�​ ​L​o​a​d​i​n​g​ ​a​t​ ​t​h​e​ ​s​p​e​e​d​ ​o​f​ ​a​ ​b​a​l​l​a​d​.​.​.
     */
    '17': string;
    /**
     * �​�​ ​T​u​n​i​n​g​ ​t​h​e​ ​p​i​a​n​o​ ​k​e​y​s​.​.​.
     */
    '18': string;
    /**
     * �​�​ ​T​e​s​t​i​n​g​ ​t​h​e​ ​s​p​e​a​k​e​r​s​:​ ​O​n​e​,​ ​t​w​o​,​ ​t​h​r​e​e​.​.​.
     */
    '19': string;
  };
  theme: {
    /**
     * T​o​g​g​l​e​ ​t​h​e​m​e
     */
    toggle: string;
    /**
     * L​i​g​h​t
     */
    light: string;
    /**
     * D​a​r​k
     */
    dark: string;
    /**
     * S​y​s​t​e​m
     */
    system: string;
    /**
     * C​u​r​r​e​n​t​ ​t​h​e​m​e​:​ ​{​0​}
     * @param {unknown} 0
     */
    current: RequiredParams<'0'>;
  };
  chromeAI: {
    /**
     * L​o​c​a​l​ ​t​r​a​n​s​l​a​t​i​o​n
     */
    useBrowserAI: string;
    /**
     * B​e​t​a
     */
    beta: string;
    /**
     * D​o​w​n​l​o​a​d​i​n​g​.​.​.
     */
    downloading: string;
    /**
     * R​e​a​d​y
     */
    modelReady: string;
    /**
     * E​r​r​o​r
     */
    modelError: string;
    /**
     * T​r​a​n​s​l​a​t​e​d​ ​l​o​c​a​l​l​y​ ​(​o​f​f​l​i​n​e​)
     */
    localTranslationTooltip: string;
    /**
     * A​v​a​i​l​a​b​l​e​ ​f​o​r​ ​l​o​c​a​l​ ​t​r​a​n​s​l​a​t​i​o​n​ ​(​r​e​q​u​i​r​e​s​ ​d​o​w​n​l​o​a​d​)
     */
    downloadableTooltip: string;
    /**
     * S​o​m​e​ ​l​a​n​g​u​a​g​e​s​ ​m​a​y​ ​n​o​t​ ​b​e​ ​a​v​a​i​l​a​b​l​e​.​ ​C​l​o​u​d​ ​t​r​a​n​s​l​a​t​i​o​n​ ​w​i​l​l​ ​b​e​ ​u​s​e​d​ ​a​s​ ​f​a​l​l​b​a​c​k​.​ ​L​o​c​a​l​ ​t​r​a​n​s​l​a​t​i​o​n​s​ ​m​a​y​ ​b​e​ ​l​e​s​s​ ​a​c​c​u​r​a​t​e​.
     */
    disclaimer: string;
  };
  pwa: {
    /**
     * N​e​w​ ​v​e​r​s​i​o​n​ ​a​v​a​i​l​a​b​l​e
     */
    newVersionAvailable: string;
    /**
     * R​e​l​o​a​d
     */
    reload: string;
    /**
     * C​l​o​s​e
     */
    close: string;
  };
  demoMode: {
    /**
     * D​e​m​o​ ​M​o​d​e
     */
    title: string;
    /**
     * T​o​g​g​l​e​ ​d​e​m​o​ ​m​o​d​e
     */
    toggle: string;
    /**
     * D​e​m​o
     */
    badge: string;
    /**
     * T​r​y​ ​t​h​e​ ​a​p​p​ ​w​i​t​h​ ​p​r​e​-​l​o​a​d​e​d​ ​d​e​m​o​ ​v​i​d​e​o​s
     */
    description: string;
  };
  meta: {
    /**
     * W​a​t​c​h​ ​o​n​ ​L​y​r​i​a
     */
    description: string;
  };
};

export type TranslationFunctions = {
  /**
   * Lyria
   */
  appName: () => LocalizedString;
  search: {
    /**
     * Search by artist or song in your recents, or paste a YouTube URL
     */
    placeholder: () => LocalizedString;
    /**
     * Load Video
     */
    loadVideo: () => LocalizedString;
    /**
     * This video is not in your history
     */
    notInHistory: () => LocalizedString;
    /**
     * Press Enter to load it
     */
    pressEnterToLoad: () => LocalizedString;
    /**
     * No results found
     */
    noResults: () => LocalizedString;
    /**
     * Try searching by artist or song, or paste a YouTube URL
     */
    searchHint: () => LocalizedString;
    /**
     * All
     */
    all: () => LocalizedString;
    /**
     * Favorites
     */
    favorites: () => LocalizedString;
  };
  video: {
    /**
     * Unplayed
     */
    unplayed: () => LocalizedString;
  };
  videoError: {
    /**
     * Video Unavailable
     */
    title: () => LocalizedString;
    /**
     * This video ID is invalid.
     */
    invalidId: () => LocalizedString;
    /**
     * This video was not found or has been removed.
     */
    notFound: () => LocalizedString;
    /**
     * This video cannot be played here.
     */
    notPlayable: () => LocalizedString;
    /**
     * An error occurred while loading the video.
     */
    genericError: () => LocalizedString;
    /**
     * Go Back
     */
    goBack: () => LocalizedString;
  };
  lyrics: {
    /**
     * Original Lyrics
     */
    original: () => LocalizedString;
    /**
     * Translated Lyrics
     */
    translated: () => LocalizedString;
    /**
     * Lyrics on their way! Just a little wait!... ✍️
     */
    loading: () => LocalizedString;
    /**
     * No lyrics found for this song
     */
    notFound: () => LocalizedString;
    /**
     * Hide original subtitles
     */
    hideOriginal: () => LocalizedString;
    /**
     * Show original subtitles
     */
    showOriginal: () => LocalizedString;
    /**
     * Hide translated subtitles
     */
    hideTranslated: () => LocalizedString;
    /**
     * Show translated subtitles
     */
    showTranslated: () => LocalizedString;
  };
  lyricSelector: {
    /**
     * Select Lyrics
     */
    title: () => LocalizedString;
    /**
     * Automatic Selection
     */
    automatic: () => LocalizedString;
    /**
     * Let the app choose
     */
    automaticDescription: () => LocalizedString;
    /**
     * No lyrics found
     */
    noLyrics: () => LocalizedString;
    /**
     * Synced
     */
    synced: () => LocalizedString;
    /**
     * Plain
     */
    plain: () => LocalizedString;
    /**
     * Close
     */
    close: () => LocalizedString;
    /**
     * Search for lyrics...
     */
    searchPlaceholder: () => LocalizedString;
    /**
     * Searching...
     */
    searching: () => LocalizedString;
    /**
     * Type a song or artist name to search
     */
    searchHint: () => LocalizedString;
  };
  controls: {
    /**
     * Original
     */
    original: () => LocalizedString;
    /**
     * Translated
     */
    translated: () => LocalizedString;
    /**
     * Copy URL
     */
    copyUrl: () => LocalizedString;
    /**
     * Sync with current time
     */
    syncWithCurrentTime: () => LocalizedString;
    /**
     * Delete video
     */
    deleteVideo: () => LocalizedString;
    /**
     * Play
     */
    play: () => LocalizedString;
    /**
     * Pause
     */
    pause: () => LocalizedString;
    /**
     * Mute
     */
    mute: () => LocalizedString;
    /**
     * Unmute
     */
    unmute: () => LocalizedString;
    /**
     * Enter fullscreen
     */
    enterFullscreen: () => LocalizedString;
    /**
     * Exit fullscreen
     */
    exitFullscreen: () => LocalizedString;
    /**
     * Decrease timing offset
     */
    decreaseTimingOffset: () => LocalizedString;
    /**
     * Increase timing offset
     */
    increaseTimingOffset: () => LocalizedString;
    /**
     * Click to start
     */
    clickToStart: () => LocalizedString;
    /**
     * Loading...
     */
    loading: () => LocalizedString;
  };
  footer: {
    /**
     * View on GitHub
     */
    github: () => LocalizedString;
    /**
     * Released under the {license} License
     */
    license: (arg: { license: unknown }) => LocalizedString;
    /**
     * Created with passion by {author}
     */
    author: (arg: { author: unknown }) => LocalizedString;
    /**
     * MIT
     */
    mit: () => LocalizedString;
    /**
     * Javier López Medina
     */
    authorName: () => LocalizedString;
  };
  languages: {
    /**
     * English
     */
    en: () => LocalizedString;
    /**
     * Spanish
     */
    es: () => LocalizedString;
  };
  lyricsLanguages: {
    /**
     * Arabic
     */
    AR: () => LocalizedString;
    /**
     * Bulgarian
     */
    BG: () => LocalizedString;
    /**
     * Czech
     */
    CS: () => LocalizedString;
    /**
     * Danish
     */
    DA: () => LocalizedString;
    /**
     * German
     */
    DE: () => LocalizedString;
    /**
     * Greek
     */
    EL: () => LocalizedString;
    /**
     * English (British)
     */
    'EN-GB': () => LocalizedString;
    /**
     * English (American)
     */
    'EN-US': () => LocalizedString;
    /**
     * Spanish
     */
    ES: () => LocalizedString;
    /**
     * Spanish (Latin American)
     */
    'ES-419': () => LocalizedString;
    /**
     * Estonian
     */
    ET: () => LocalizedString;
    /**
     * Finnish
     */
    FI: () => LocalizedString;
    /**
     * French
     */
    FR: () => LocalizedString;
    /**
     * Hebrew
     */
    HE: () => LocalizedString;
    /**
     * Hungarian
     */
    HU: () => LocalizedString;
    /**
     * Indonesian
     */
    ID: () => LocalizedString;
    /**
     * Italian
     */
    IT: () => LocalizedString;
    /**
     * Japanese
     */
    JA: () => LocalizedString;
    /**
     * Korean
     */
    KO: () => LocalizedString;
    /**
     * Lithuanian
     */
    LT: () => LocalizedString;
    /**
     * Latvian
     */
    LV: () => LocalizedString;
    /**
     * Norwegian Bokmål
     */
    NB: () => LocalizedString;
    /**
     * Dutch
     */
    NL: () => LocalizedString;
    /**
     * Polish
     */
    PL: () => LocalizedString;
    /**
     * Portuguese (Brazilian)
     */
    'PT-BR': () => LocalizedString;
    /**
     * Portuguese (Portugal)
     */
    'PT-PT': () => LocalizedString;
    /**
     * Romanian
     */
    RO: () => LocalizedString;
    /**
     * Russian
     */
    RU: () => LocalizedString;
    /**
     * Slovak
     */
    SK: () => LocalizedString;
    /**
     * Slovenian
     */
    SL: () => LocalizedString;
    /**
     * Swedish
     */
    SV: () => LocalizedString;
    /**
     * Thai
     */
    TH: () => LocalizedString;
    /**
     * Turkish
     */
    TR: () => LocalizedString;
    /**
     * Ukrainian
     */
    UK: () => LocalizedString;
    /**
     * Vietnamese
     */
    VI: () => LocalizedString;
    /**
     * Chinese
     */
    ZH: () => LocalizedString;
    /**
     * Chinese (simplified)
     */
    'ZH-HANS': () => LocalizedString;
    /**
     * Chinese (traditional)
     */
    'ZH-HANT': () => LocalizedString;
  };
  time: {
    /**
     * {0} second{{s}} ago
     */
    secondsAgo: (arg0: string | number | boolean) => LocalizedString;
    /**
     * {0} minute{{s}} ago
     */
    minutesAgo: (arg0: string | number | boolean) => LocalizedString;
    /**
     * {0} hour{{s}} ago
     */
    hoursAgo: (arg0: string | number | boolean) => LocalizedString;
    /**
     * {0} day{{s}} ago
     */
    daysAgo: (arg0: string | number | boolean) => LocalizedString;
    /**
     * {0} week{{s}} ago
     */
    weeksAgo: (arg0: string | number | boolean) => LocalizedString;
    /**
     * {0} month{{s}} ago
     */
    monthsAgo: (arg0: string | number | boolean) => LocalizedString;
    /**
     * {0} year{{s}} ago
     */
    yearsAgo: (arg0: string | number | boolean) => LocalizedString;
  };
  loadingPhrases: {
    /**
     * 🎵 Loading your jam...
     */
    '0': () => LocalizedString;
    /**
     * 🎸 Tuning the air guitar...
     */
    '1': () => LocalizedString;
    /**
     * 🎤 Warming up the vocal cords...
     */
    '2': () => LocalizedString;
    /**
     * 🔑 Finding the right key...
     */
    '3': () => LocalizedString;
    /**
     * ✨ Polishing the microphone...
     */
    '4': () => LocalizedString;
    /**
     * 🥁 Syncing with the rhythm...
     */
    '5': () => LocalizedString;
    /**
     * 😴 Asking the drummer to wake up...
     */
    '6': () => LocalizedString;
    /**
     * 🔓 Unlocking the groove...
     */
    '7': () => LocalizedString;
    /**
     * 💾 Loading data... or at least pretending to.
     */
    '8': () => LocalizedString;
    /**
     * 🧮 Calculating the exact number of nanoseconds you will wait.
     */
    '9': () => LocalizedString;
    /**
     * ⏳ Almost there... (but not quite).
     */
    '10': () => LocalizedString;
    /**
     * 💬 Loading the message that says “Loading…”.
     */
    '11': () => LocalizedString;
    /**
     * 🎡 Simulating progress to keep you entertained.
     */
    '12': () => LocalizedString;
    /**
     * 🎤 Looking for the lyrics… seems the singer doesn’t know them either.
     */
    '13': () => LocalizedString;
    /**
     * 🎧 Convincing the DJ to press play...
     */
    '14': () => LocalizedString;
    /**
     * 🎼 Rehearsing the chorus one last time...
     */
    '15': () => LocalizedString;
    /**
     * 🕺 Practicing dance moves while you wait...
     */
    '16': () => LocalizedString;
    /**
     * 🐢 Loading at the speed of a ballad...
     */
    '17': () => LocalizedString;
    /**
     * 🎹 Tuning the piano keys...
     */
    '18': () => LocalizedString;
    /**
     * 📢 Testing the speakers: One, two, three...
     */
    '19': () => LocalizedString;
  };
  theme: {
    /**
     * Toggle theme
     */
    toggle: () => LocalizedString;
    /**
     * Light
     */
    light: () => LocalizedString;
    /**
     * Dark
     */
    dark: () => LocalizedString;
    /**
     * System
     */
    system: () => LocalizedString;
    /**
     * Current theme: {0}
     */
    current: (arg0: unknown) => LocalizedString;
  };
  chromeAI: {
    /**
     * Local translation
     */
    useBrowserAI: () => LocalizedString;
    /**
     * Beta
     */
    beta: () => LocalizedString;
    /**
     * Downloading...
     */
    downloading: () => LocalizedString;
    /**
     * Ready
     */
    modelReady: () => LocalizedString;
    /**
     * Error
     */
    modelError: () => LocalizedString;
    /**
     * Translated locally (offline)
     */
    localTranslationTooltip: () => LocalizedString;
    /**
     * Available for local translation (requires download)
     */
    downloadableTooltip: () => LocalizedString;
    /**
     * Some languages may not be available. Cloud translation will be used as fallback. Local translations may be less accurate.
     */
    disclaimer: () => LocalizedString;
  };
  pwa: {
    /**
     * New version available
     */
    newVersionAvailable: () => LocalizedString;
    /**
     * Reload
     */
    reload: () => LocalizedString;
    /**
     * Close
     */
    close: () => LocalizedString;
  };
  demoMode: {
    /**
     * Demo Mode
     */
    title: () => LocalizedString;
    /**
     * Toggle demo mode
     */
    toggle: () => LocalizedString;
    /**
     * Demo
     */
    badge: () => LocalizedString;
    /**
     * Try the app with pre-loaded demo videos
     */
    description: () => LocalizedString;
  };
  meta: {
    /**
     * Watch on Lyria
     */
    description: () => LocalizedString;
  };
};

export type Formatters = {};
